import { TypeIR, FieldIR } from './ir'

function formatComment(comment?: string, indent = ''): string {
  if (!comment) return ''
  return `${indent}// ${comment}\n`
}

function formatField(field: FieldIR, indent = '\t'): string {
  let line = ''
  if (field.comment) {
    line += `${indent}// ${field.comment}\n`
  }
  line += `${indent}${field.goName} ${field.goType} \`${field.jsonTag}\``
  return line
}

function generateStruct(type: TypeIR): string {
  let out = formatComment(type.comment)
  out += `type ${type.goName} struct {\n`
  for (const field of type.fields) {
    out += formatField(field) + '\n'
  }
  out += '}\n'
  return out
}

function generateStringEnum(type: TypeIR): string {
  const constName = type.goName
  let out = formatComment(type.comment)
  out += `type ${constName} string\n\n`
  out += 'const (\n'
  for (const field of type.fields) {
    const val = field.name
    const constValue = `${constName}${field.goName}`
    out += `\t${constValue} ${constName} = "${val}"\n`
  }
  out += ')\n'
  return out
}

function generateTypeAlias(type: TypeIR): string {
  const value = type.fields[0]?.goType || 'interface{}'
  let out = formatComment(type.comment)
  out += `type ${type.goName} = ${value}\n`
  return out
}

export function generateGoCode(types: TypeIR[]): string {
  const lines: string[] = []
  lines.push('// Code generated by ec-warden-auth generate. DO NOT EDIT.')
  lines.push('')
  lines.push('package wardenauth')
  lines.push('')

  const generatedNames = new Set<string>()

  for (const type of types) {
    if (generatedNames.has(type.goName)) continue
    generatedNames.add(type.goName)

    switch (type.kind) {
      case 'struct':
        lines.push(generateStruct(type))
        break
      case 'string-enum':
        lines.push(generateStringEnum(type))
        break
      case 'type-alias':
        lines.push(generateTypeAlias(type))
        break
    }
  }

  return lines.join('\n') + '\n'
}
